(add-to-list 'load-path (concat emacs-lib-dir "/emacs-w3m"))
(require 'w3m-load)
(setq browse-url-browser-function 'w3m-browse-url)
(autoload 'w3m-browse-url "w3m" "Ask a WWW browser to show a URL." t)
(global-set-key "\C-xm" 'browse-url-at-point)
(setq w3m-use-cookies t)
(setq w3m-add-referer t)
(setq w3m-follow-redirection 10)
